version: '3.7'

services:
  db:
    container_name: constantia_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

  web:
    container_name: constantia_backend
    build: ./web
    command: python3.7 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  client:
    container_name: constantia_client
    build: ./client
    command: yarn serve
    ports:
      - 8080:8080
    volumes:
      - ./client/:/usr/src/client/
    depends_on:
      - web
      - db
    env_file:
      - .env.dev

volumes:
  postgres_data:
